#!/usr/bin/env node
/**
 * Borrow the app's own stylesheet rules for the components the registry's
 * playlist page reuses (the spinning disc, the cover wall), so the page wears
 * exactly what the app wears and follows it when it changes.
 *
 * Pulls every rule whose selector names one of the borrowed classes, plus
 * every @keyframes those rules animate with, out of the app's style chunks
 * into src/landing/borrowed.css. Run by `npm run build:landing`; the output
 * is generated, never edited.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const STYLES = 'src/app/styles';
const OUT = 'src/landing/borrowed.css';
const CLASSES = ['spinningDisc', 'coverWall'];

const css = readdirSync(STYLES)
  .filter((f) => f.endsWith('.css'))
  .sort()
  .map((f) => readFileSync(join(STYLES, f), 'utf8'))
  .join('\n');

// Strip comments, then walk top-level blocks. Nested at-rules (@media,
// @supports) are kept whole when anything inside names a borrowed class.
const clean = css.replace(/\/\*[\s\S]*?\*\//g, '');
const wanted = new RegExp(`\\.(${CLASSES.join("|")})(?:__[\\w-]+)?(?![\\w-])`);

const blocks = [];
let depth = 0;
let start = 0;
for (let i = 0; i < clean.length; i++) {
  const ch = clean[i];
  if (ch === '{') {
    if (depth === 0) start = clean.lastIndexOf('}', i) + 1;
    depth++;
  } else if (ch === '}') {
    depth--;
    if (depth === 0) blocks.push(clean.slice(start, i + 1).trim());
  }
}

const kept = blocks.filter((b) => {
  const selector = b.slice(0, b.indexOf('{'));
  if (selector.trim().startsWith('@keyframes')) return false;
  return wanted.test(b);
});
const animations = new Set();
for (const b of kept) {
  for (const m of b.matchAll(/animation(?:-name)?\s*:\s*([^;]+);/g)) {
    for (const token of m[1].split(/[\s,]+/)) {
      if (/^[A-Za-z_][\w-]*$/.test(token) && !/^(infinite|linear|ease|alternate|forwards|backwards|both|normal|reverse|paused|running|none)$/.test(token))
        animations.add(token);
    }
  }
}
const keyframes = blocks.filter((b) => {
  const m = b.match(/^@keyframes\s+([\w-]+)/);
  return m && animations.has(m[1]);
});

const out = `/* GENERATED by scripts/landing-borrow.mjs - the app's own rules for ${CLASSES.map((c) => '.' + c).join(', ')}. Do not edit. */\n\n${[...keyframes, ...kept].join('\n\n')}\n`;
writeFileSync(OUT, out);
console.log(`borrowed ${kept.length} rules and ${keyframes.length} keyframes into ${OUT}`);
